# Generated by Django 3.2.6 on 2022-04-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_number', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='종목번호')),
                ('stock_name', models.CharField(max_length=20, unique=True, verbose_name='종목명')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_trade_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_dttm', models.DateTimeField(verbose_name='날짜')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('middle_price', models.FloatField(verbose_name='중가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('end_price', models.FloatField(verbose_name='종가')),
                ('volume', models.FloatField(verbose_name='거래량')),
                ('stock_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='종목번호')),
            ],
        ),
    ]
