# Generated by Django 3.2.6 on 2022-04-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTradeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_dttm', models.DateTimeField(verbose_name='날짜')),
                ('high_price', models.FloatField(verbose_name='고가')),
                ('middle_price', models.FloatField(verbose_name='중가')),
                ('low_price', models.FloatField(verbose_name='저가')),
                ('end_price', models.FloatField(verbose_name='종가')),
                ('volume', models.FloatField(verbose_name='거래량')),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='종목번호'),
        ),
        migrations.DeleteModel(
            name='Stock_trade_info',
        ),
        migrations.AddField(
            model_name='stocktradeinfo',
            name='stock_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='종목번호'),
        ),
    ]
