# Generated by Django 3.2.6 on 2022-04-20 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0002_auto_20220421_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockModel',
            fields=[
                ('model_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='모델번호')),
                ('model_name', models.CharField(max_length=12, verbose_name='모델명')),
                ('description', models.TextField(verbose_name='상세정보')),
            ],
        ),
        migrations.CreateModel(
            name='StockModelTradeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.DateField(verbose_name='날짜')),
                ('trade_type', models.CharField(max_length=5, verbose_name='거래종류')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockmodel', verbose_name='모델번호')),
                ('stock_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='종목명')),
            ],
        ),
        migrations.CreateModel(
            name='StockModelPredictDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_day', models.DateField(verbose_name='예측날짜')),
                ('predicted_day_out', models.CharField(max_length=100, verbose_name='당일예측결과')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockmodel', verbose_name='모델번호')),
            ],
        ),
        migrations.CreateModel(
            name='StockModelPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_day', models.DateField(verbose_name='예측날짜')),
                ('predicted_out', models.FloatField(verbose_name='예측결과')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockmodel', verbose_name='모델번호')),
                ('stock_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.stock', verbose_name='종목명')),
            ],
        ),
        migrations.CreateModel(
            name='StockModelDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_day', models.DateField(verbose_name='날짜')),
                ('bought_items', models.CharField(max_length=128, verbose_name='당일매수종목')),
                ('sold_items', models.CharField(max_length=128, verbose_name='당일매도종목')),
                ('yields', models.FloatField(verbose_name='수익률')),
                ('cash', models.IntegerField(verbose_name='총 자금')),
                ('items', models.CharField(max_length=128, verbose_name='현재주식')),
                ('model_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_models.stockmodel', verbose_name='모델번호')),
            ],
        ),
    ]
