# Generated by Django 3.2.6 on 2022-04-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodelpredictday',
            name='predicted_day_out',
            field=models.TextField(verbose_name='당일예측결과'),
        ),
    ]
